### ISSUE TITLE
NRE when compiling a module with an invalid CLI profile

### ISSUE THREAD

**Issue by bjorg** [LambdaSharp/LambdaSharpTool#100]
The following exception occurs when compiling a module with an invalid CLI profile:
```
LambdaSharp CLI (v0.5.0.1) - Build LambdaSharp module

Compiling module: Module.yml

FAILED: 1 errors encountered
ERROR: internal error: One or more errors occurred. (Object reference not set to an instance of an object.)
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at LambdaSharp.Tool.ModelManifestLoader.LocateAsync(String moduleOwner, String moduleName, VersionInfo minVersion, VersionInfo maxVersion, String bucketName) in C:\MindTouch\LambdaSharpTool\src\LambdaSharp.Tool\ModelManifestLoader.cs:line 133
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at LambdaSharp.Tool.Model.ModuleBuilder.AddDependency(String moduleFullName, VersionInfo minVersion, VersionInfo maxVersion, String bucketName) in C:\MindTouch\LambdaSharpTool\src\LambdaSharp.Tool\Model\ModuleBuilder.cs:line 276
   at LambdaSharp.Tool.Cli.Build.ModelModuleInitializer.Initialize(ModuleBuilder builder) in C:\MindTouch\LambdaSharpTool\src\LambdaSharp.Tool\Cli\Build\ModelModuleInitializer.cs:line 570
   at LambdaSharp.Tool.Cli.Build.BuildStep.DoAsync(String outputCloudFormationFilePath, Boolean noAssemblyValidation, Boolean noPackageBuild, String gitSha, String gitBranch, String buildConfiguration, String selector) in C:\MindTouch\LambdaSharpTool\src\LambdaSharp.Tool\Cli\Build\BuildStep.cs:line 74
   at LambdaSharp.Tool.Cli.CliBuildPublishDeployCommand.BuildStepAsync(Settings settings, String outputCloudFormationFilePath, Boolean noAssemblyValidation, Boolean noPackageBuild, String gitSha, String gitBranch, String buildConfiguration, String selector, String moduleSource) in C:\MindTouch\LambdaSharpTool\src\LambdaSharp.Tool\Cli\CliBuildCommand.cs:line 487
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at LambdaSharp.Tool.ModelManifestLoader.LocateAsync(String moduleOwner, String moduleName, VersionInfo minVersion, VersionInfo maxVersion, String bucketName) in C:\MindTouch\LambdaSharpTool\src\LambdaSharp.Tool\ModelManifestLoader.cs:line 133<---
```

**Comment by bjorg** [comment]
Released in v0.5.0.2
