### ISSUE TITLE
InvalidCastException when setting Secrets in the parameters file

### ISSUE THREAD

**Issue by bjorg** [LambdaSharp/LambdaSharpTool#93]
The following parameters.yml file causes an `InvalidCastException`:
```yaml
HostName: db-content.REMOVED
Password: REMOVED
Username: REMOVED
VPCSecurityGroupId: sg-REMOVED
VPCSubnetIds: subnet-REMOVED,subnet-REMOVED
Secrets: alias/encryption-key-alias
```

Error:
```
LambdaSharp CLI (v0.5) - Deploy LambdaSharp module

FAILED: 1 errors encountered
ERROR: internal error: Unable to cast object of type 'System.Collections.Generic.List`1[System.String]' to type 'System.Collections.Generic.IList`1[System.Object]'.
System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.List`1[System.String]' to type 'System.Collections.Generic.IList`1[System.Object]'.
   at LambdaSharp.Tool.Cli.CliBuildPublishDeployCommand.<>c.<ReadInputParametersFiles>b__10_1(KeyValuePair`2 kv) in /Users/juant/Code/LambdaSharpTool/src/LambdaSharp.Tool/Cli/CliBuildCommand.cs:line 128
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at LambdaSharp.Tool.Cli.CliBuildPublishDeployCommand.ReadInputParametersFiles(Settings settings, String filename) in /Users/juant/Code/LambdaSharpTool/src/LambdaSharp.Tool/Cli/CliBuildCommand.cs:line 126
```

Removing the `Secrets` section fixes the exception.

**Comment by bjorg** [comment]
Released in v0.5.0.1
